# Generated by Django 4.2.2 on 2023-06-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='HelpReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('help_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.help')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.user')),
            ],
        ),
    ]
