# Generated by Django 4.2.2 on 2023-06-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_help_helpreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_email', models.EmailField(max_length=30)),
                ('vehicle_num', models.CharField(max_length=20)),
                ('license_num', models.CharField(max_length=20)),
                ('sloc', models.CharField(max_length=50)),
                ('dloc', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_email', models.EmailField(max_length=30)),
                ('sloc', models.CharField(max_length=50)),
                ('dloc', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
