# Generated by Django 4.2.2 on 2023-06-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0003_drive_ride'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_email', models.EmailField(max_length=30)),
                ('d_email', models.EmailField(max_length=30)),
                ('sloc', models.CharField(max_length=50)),
                ('dloc', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
    ]
