# Generated by Django 5.0.1 on 2024-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0006_drive_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='address',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
