# Generated by Django 5.0.1 on 2024-03-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0007_ride_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebook',
            name='address',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
