# Generated by Django 5.0.1 on 2024-03-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0008_ridebook_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ridebook',
            name='address',
        ),
    ]
