# Generated by Django 5.0.1 on 2024-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0009_remove_ride_address_remove_ridebook_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='address',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='ridebook',
            name='address',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
