# Generated by Django 5.0.6 on 2024-08-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicleapp", "0010_ride_address_ridebook_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="drive",
            name="Price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
