# Generated by Django 5.0.6 on 2024-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicleapp", "0011_drive_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridebook",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
