# Generated by Django 5.0.6 on 2024-09-05 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicleapp", "0012_alter_ridebook_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drive",
            old_name="Price",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="ridebook",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicleapp.user",
                    ),
                ),
            ],
        ),
    ]
