# Generated by Django 5.0.6 on 2024-09-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicleapp", "0013_rename_price_drive_price_alter_ridebook_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridebook",
            name="payment_required",
            field=models.BooleanField(default=False),
        ),
    ]
