# Generated by Django 5.0.6 on 2024-09-05 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicleapp", "0016_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
